language: clojure

script:
  - lein test
  - lein eastwood
  - lein kibit
  - lein cloverage

jdk:
  - oraclejdk8

sudo: required

after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
